### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by MPavicevic** [RAMP-project/RAMP-mobility#7]
Im not a license expert like some guys at the OpenMod community. But it might be a good idea to check this [link](
https://joinup.ec.europa.eu/collection/eupl/news/eupl-or-gplv3-comparison-t) and decide if this tool is EUPL (1.2 and not 1.1 because 1.1 is outdated) or GPL

**Comment by FLomb** [comment]
License updated to 1.2-or-later
