### ISSUE TITLE
Good practice for python packages

### ISSUE THREAD

**Issue by MPavicevic** [RAMP-project/RAMP-mobility#8]
If we have big plans with this project it would be wise to restructure the repo a bit like this good practice [guidelines](https://dev.to/codemouse92/dead-simple-python-project-structure-and-imports-38c6) suggest. Better now when the project is young then later when you add more and more stuff. It should take only couple of commits and it will make the maintenance of the project way easier.

**Comment by Mangips** [comment]
I created a branch called "repository restructure" to address this, where the structure is more in line with the guidelines.
